In [9]:
import numpy as np
import pandas as pd
import random 
from decpomdp import DecPOMDP



In [10]:
from decpomdp import DecPOMDP
horizon = 5
cooperative_game = DecPOMDP("dectiger",1 , horizon )
competitive_game = DecPOMDP("dectiger_competitive",2,  horizon = horizon)



In [11]:
print(min([min(row)for row in cooperative_game.reward_fn_sa]))

-101.0


In [12]:
cooperative_game.joint_actions

[('listen', 'listen'),
 ('listen', 'open-left'),
 ('listen', 'open-right'),
 ('open-left', 'listen'),
 ('open-left', 'open-left'),
 ('open-left', 'open-right'),
 ('open-right', 'listen'),
 ('open-right', 'open-left'),
 ('open-right', 'open-right')]

In [13]:
import random
def follower_stackelberg_reward():
    # set fixed seed
    seed_value = 42
    random.seed(seed_value)

    #initialize rewards
    stackelberg_follower_reward = np.zeros(cooperative_game.reward_fn_sa.shape)

    # set min and max range of random number
    min = min([min(row)for row in cooperative_game.reward_fn_sa])
    max = max([max(row) for row in cooperative_game.reward_fn_sa])

    # Generate five random integers between 1 and 10
    for joint_action in range(5):
        for state in range(2):
            stackelberg_follower_reward[joint_action][state]=random.randint(min, max)


In [14]:
competitive_game.joint_actions[0]

('listen', 'listen')

In [44]:
new = competitive_game.observation_fn.reshape((competitive_game.num_joint_actions,competitive_game.num_joint_observations,len(competitive_game.states)))
a = np.array([[[2,3],[4,5]],[[6,7],[8,9]]])
flipped_array = np.flip(a, axis=(1,2))
flipped_array[0]

array([[5, 4],
       [3, 2]])

In [46]:
a[0]

array([[2, 3],
       [4, 5]])

In [17]:
a = np.zeros((cooperative_game.num_joint_actions,len(cooperative_game.states)))
a[2] += cooperative_game.reward_fn_sa[3]
a

array([[   0.,    0.],
       [   0.,    0.],
       [-101.,    9.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.]])

In [18]:
cooperative_game.reward_fn_sa

array([[  -2.,   -2.],
       [-101.,    9.],
       [   9., -101.],
       [-101.,    9.],
       [ -50.,   20.],
       [-100., -100.],
       [   9., -101.],
       [-100., -100.],
       [  20.,  -50.]])

In [19]:
np.zeros((2,9,4))[0][2][2]

0.0