In [10]:
import numpy as np
import pandas as pd
import random 
from docplex.cp.config import context
from docplex.mp.model import Model
from docplex.mp.context import Context as C


ModuleNotFoundError: No module named 'docplex.cp.context'

In [6]:
C().solver

{'log_output': False,
 'max_threads': None,
 'auto_publish': {'solve_details': False,
  'result_output': None,
  'kpis_output': None,
  'kpis_output_field_name': None,
  'kpis_output_field_value': None,
  'relaxations_output': None,
  'conflicts_output': None},
 'kpi_reporting': {'filter_level': <ProgressClock.Gap: 7>}}

In [ ]:
from decpomdp import DecPOMDP
horizon = 5
cooperative_game = DecPOMDP("dectiger",1 , horizon )
competitive_game = DecPOMDP("dectiger_competitive",2,  horizon = horizon)



In [ ]:
print(min([min(row)for row in cooperative_game.reward_fn_sa]))

-101.0


In [ ]:
cooperative_game.joint_actions

[('listen', 'listen'),
 ('listen', 'open-left'),
 ('listen', 'open-right'),
 ('open-left', 'listen'),
 ('open-left', 'open-left'),
 ('open-left', 'open-right'),
 ('open-right', 'listen'),
 ('open-right', 'open-left'),
 ('open-right', 'open-right')]

In [ ]:
import random
def follower_stackelberg_reward():
    # set fixed seed
    seed_value = 42
    random.seed(seed_value)

    #initialize rewards
    stackelberg_follower_reward = np.zeros(cooperative_game.reward_fn_sa.shape)

    # set min and max range of random number
    min = min([min(row)for row in cooperative_game.reward_fn_sa])
    max = max([max(row) for row in cooperative_game.reward_fn_sa])

    # Generate five random integers between 1 and 10
    for joint_action in range(5):
        for state in range(2):
            stackelberg_follower_reward[joint_action][state]=random.randint(min, max)


In [ ]:
competitive_game.joint_actions[0]

('listen', 'listen')

In [ ]:
competitive_game.joint_actions[0]


('listen', 'listen')

In [ ]:
cooperative_game.reward_fn_sa[0]

array([-2., -2.])

In [ ]:
a = np.zeros((cooperative_game.num_joint_actions,len(cooperative_game.states)))
a[2] += cooperative_game.reward_fn_sa[3]
a

array([[   0.,    0.],
       [   0.,    0.],
       [-101.,    9.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.]])

In [ ]:
cooperative_game.reward_fn_sa

array([[  -2.,   -2.],
       [-101.,    9.],
       [   9., -101.],
       [-101.,    9.],
       [ -50.,   20.],
       [-100., -100.],
       [   9., -101.],
       [-100., -100.],
       [  20.,  -50.]])

In [ ]:
np.zeros((2,9,4))[0][2][2]

0.0