In [1]:
import numpy as np
import pandas as pd
import random 

In [1]:
from decpomdp import DecPOMDP
horizon = 5
cooperative_game = DecPOMDP("prisoners",1 , horizon )



In [11]:
cooperative_game.reward_fn_sa

array([[ -1.],
       [-10.],
       [  0.],
       [ -5.]])

In [14]:
print(max([min(row)for row in cooperative_game.reward_fn_sa]))

0.0


In [10]:
cooperative_game.joint_actions

cooperative_game.get_seperate_action(3)

(1, 1)

In [30]:
import random
def follower_stackelberg_reward():
    # set fixed seed
    seed_value = 42
    random.seed(seed_value)

    #initialize rewards
    stackelberg_follower_reward = np.zeros(cooperative_game.reward_fn_sa.shape)

    # set min and max range of random number
    min = min([min(row)for row in cooperative_game.reward_fn_sa])
    max = max([max(row) for row in cooperative_game.reward_fn_sa])

    # Generate five random integers between 1 and 10
    for joint_action in range(5):
        for state in range(2):
            stackelberg_follower_reward[joint_action][state]=random.randint(min, max)


In [5]:
competitive_game.joint_actions[0]

('listen', 'listen')

In [6]:
competitive_game.joint_actions[0]


('listen', 'listen')

In [7]:
cooperative_game.reward_fn_sa[0]

array([-2., -2.])

In [43]:
a = np.zeros((cooperative_game.num_joint_actions,len(cooperative_game.states)))
a[2] += cooperative_game.reward_fn_sa[3]
a

array([[   0.,    0.],
       [   0.,    0.],
       [-101.,    9.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.]])

In [50]:
cooperative_game.reward_fn_sa

array([[  -2.,   -2.],
       [-101.,    9.],
       [   9., -101.],
       [-101.,    9.],
       [ -50.,   20.],
       [-100., -100.],
       [   9., -101.],
       [-100., -100.],
       [  20.,  -50.]])

In [35]:
np.zeros((2,9,4))[0][2][2]

0.0